version: '3.8'
services: 
  postgres:  
    image: postgres:17
    container_name: nestjs_pg_db
    ports:
      - "5433:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - ecommerce_network
  backend: 
    build: .
    container_name: nestjs_backend
    restart: always
    ports: 
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecommerce_network
  redis:
    image: redis:8-alpine
    container_name: nestjs_redis
    restart: always
    ports: 
      - "6379:6379"
    env_file:
      - .env
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - ecommerce_network
volumes:
  postgres_data:
  redis_data:
  
networks:
  ecommerce_network:
    driver: bridge